version: '3.7'

services:     
  kaleki-presenter:
    build:
      context: kaleki-presenter
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: pass

  frontend-main:
    build:
      context: frontend-main
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://kaleki-presenter:8080/api
    ports:
      - "80:80"
    # volumes:
    #   - "./frontend-main:/usr/src/app1"
    restart: always
    depends_on:
      - kaleki-presenter

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    restart: always
